# Generated by Django 5.0.3 on 2024-04-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('subtitulo', models.CharField(max_length=70)),
                ('cuerpo', models.CharField(max_length=10000)),
                ('autor', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
                ('imagen', models.ImageField(upload_to='')),
            ],
        ),
    ]
