# Generated by Django 5.0.3 on 2024-04-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0008_alumno_curso_entregable_profesor_alter_avatar_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
