# Generated by Django 5.0.3 on 2024-04-17 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0010_alter_avatar_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blog',
        ),
    ]
