# Generated by Django 5.0.3 on 2024-04-17 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0011_delete_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='foto',
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='images')),
                ('profesor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AppBlog.profesor')),
            ],
        ),
    ]
