# Generated by Django 5.0.3 on 2024-04-18 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0013_profesor_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='imagen',
        ),
    ]
