# Generated by Django 5.0.3 on 2024-04-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0014_remove_profesor_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.DeleteModel(
            name='Foto',
        ),
    ]
